import Head from 'next/head';
import {
  HomeHeroSection,
  HomeServicesSection,
  HomeLatestWorkSection,
  HomeExhibitionSection,
  HomeTestimonialSection,
  ContactSection,
} from '@/components';
import { useRecoilValue } from 'recoil';
import { preloaderAtom } from '../../atoms/preloaderAtom';

export default function Home() {
  const isLoading = useRecoilValue(preloaderAtom);
  return (
    <>
      <Head>
        <title>Jacob Grønberg | Photographer & Visual artist</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='ctn'>
          <div className={isLoading ? 'hide' : 'reveal'}>
            <HomeHeroSection />
          </div>
        </div>
        <HomeServicesSection />
        <HomeLatestWorkSection />
        <HomeExhibitionSection />
        <HomeTestimonialSection />
        <ContactSection />
      </main>
    </>
  );
}
